name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the latest version of the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment (you can specify a specific version)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Specify the Node.js version used by the project

      # Step 3: Install dependencies (if a package manager like npm or yarn is used)
      - name: Install dependencies
        run: npm install # or `yarn install` if using yarn

      # Step 4: Run tests
      - name: Run Tests
        run: npm test # Replace with the actual test command for the framework

      # Optionally, Step 5: Upload test results if you want to store them
      - name: Archive test results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results
